version: "2"

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - ineffassign

  settings:
    errcheck:
      exclude-functions:
        - (*database/sql.DB).Close
        - (*database/sql.Rows).Close
        - (*net/http.Response).Body.Close
        - (io.Closer).Close
        - os.Unsetenv

issues:
  exclude-dirs:
    - vendor
